name = "url-shortener"
main = "src/index.js"

account_id = "750f62e8572e2d2ab97bf4f84bb2a46b"
compatibility_date = "2025-01-29"

workers_dev = false
route = { pattern = "fwd.gymni.ch", custom_domain = true, zone_name = "gymni.ch" }

kv_namespaces = [ 
	 { binding = "SHORTEN", id = "846502cb8f964e22ac4b7d2c801407d0" }
]

[assets]
directory = "./dist/"
binding = "ASSETS"
run_worker_first = true

[observability.logs]
enabled = true
