name = "url-shortener"
main = "workers-site/index.js"
type = "ESModule"

account_id = "750f62e8572e2d2ab97bf4f84bb2a46b"
compatibility_date = "2022-07-12"

workers_dev = false
route = { pattern = "fwd.gymni.ch", custom_domain = true, zone_name = "gymni.ch" }

kv_namespaces = [ 
	 { binding = "SHORTEN", id = "846502cb8f964e22ac4b7d2c801407d0", preview_id = "495ee41cb63b4690afa00d50836ac201" }
]

[site]
bucket = "./public"


