name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment:
      name: production
      url: https://fwd.gymni.ch
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: cd workers-site && npm ci
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
