name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment:
      name: production
      url: https://fwd.gymni.ch
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
